<section class="card card-variant">
  <form class="createTask" action="/create" method="post">
    <div class="input-group-task">
      <div class="input-group mb-3">
        <div class="mb-3">
          <label for="time" class="form-label">Hora</label>
          <input required name="time" type="time" class="form-control" id="time">
        </div>
        <div class="mb-3">
          <label class="form-label" for="day">Dia</label>
          <select required class="form-select" name="day" id="day">
            <option selected value="td">Todos os dias</option>
            <option value="seg">Segunda</option>
            <option value="ter">Terça</option>
            <option value="qua">Quarta</option>
            <option value="qui">Quinta</option>
            <option value="sex">Sexta</option>
            <option value="sab">Sábado</option>
          </select>
        </div>
      </div>
      <div class="mb-3">
        <label for="task" class="form-label">Tarefa</label>
        <textarea required name="task" class="form-control" id="task" rows="3"></textarea>
      </div>
    </div>
    <div class="d-grid gap-2">
      <button class="btn btn-success" type="submit">Concluir</button>
      <button class="btn btn-danger" type="reset">Limpar</button>
    </div>
  </form>
</section>