<section class="card card-variant">
  <form class="createTask" action="/update-task?id=<?= $this->view->task['id'] ?>" method="post">
    <div class="input-group-task">
      <div class="input-group mb-3">
        <div class="mb-3">
          <label for="time" class="form-label">Hora</label>
          <input required name="hora" type="time" class="form-control" id="time" value="<?= $this->view->task['hora'] ?>" />
        </div>
        <div class="mb-3">
          <label class="form-label" for="day">Dia</label>
          <select required class="form-select" name="dia" id="day">
            <option value="td" <?php if ($this->view->task['dia'] == 'td') echo ' selected'; ?>>Todos os dias</option>
            <option value="seg" <?php if ($this->view->task['dia'] == 'seg') echo ' selected'; ?>>Segunda</option>
            <option value="ter" <?php if ($this->view->task['dia'] == 'ter') echo ' selected'; ?>>Terça</option>
            <option value="qua" <?php if ($this->view->task['dia'] == 'qua') echo ' selected'; ?>>Quarta</option>
            <option value="qui" <?php if ($this->view->task['dia'] == 'qui') echo ' selected'; ?>>Quinta</option>
            <option value="sex" <?php if ($this->view->task['dia'] == 'sex') echo ' selected'; ?>>Sexta</option>
            <option value="sab" <?php if ($this->view->task['dia'] == 'sab') echo ' selected'; ?>>Sábado</option>
          </select>
        </div>
      </div>
      <div class="mb-3">
        <label for="task" class="form-label">Tarefa</label>
        <textarea required name="tarefa" class="form-control" id="task" rows="3"><?= $this->view->task['tarefa'] ?></textarea>
      </div>
    </div>
    <div class="d-grid gap-2">
      <button class="btn btn-success" type="submit">Concluir</button>
      <button class="btn btn-danger" type="reset">Limpar</button>
    </div>
  </form>
</section>